name: frontend
description: "Debt Collection Management System Frontend"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  dio: ^5.4.1
  http: ^1.1.0
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true 