name: Build & Test

on:
  push:
    branches: [ "main" ]

concurrency:
  group: build-main
  cancel-in-progress: true

jobs:
  ci:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Detect release commit & bump version
        id: release
        if: startsWith(github.event.head_commit.message, 'release:')
        shell: bash
        run: |
          set -euo pipefail
          msg='${{ github.event.head_commit.message }}'
          version=$(echo "$msg" | sed -nE 's/^release:[[:space:]]*([0-9]+\.[0-9]+\.[0-9]+)$/\1/p')
          if [[ -z "$version" ]]; then
            echo "No semantic version found in release commit message. Skipping bump."
            exit 0
          fi
          echo "Detected release version: $version"
          mvn -q -f backend/pom.xml versions:set -DnewVersion="$version" -DgenerateBackupPoms=false
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add backend/pom.xml
          git commit -m "chore: release version $version [skip ci]"
          git tag "v$version"
          git push origin HEAD:main --tags
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Build & Test Backend (Maven verify)
        shell: bash
        run: |
          set -euo pipefail
          ./backend/mvnw -f backend/pom.xml clean verify

      - name: Extract Project Version
        id: projver
        shell: bash
        run: |
          set -euo pipefail
          ver=$(./backend/mvnw -q -f backend/pom.xml help:evaluate -Dexpression=project.version -DforceStdout)
          echo "version=$ver" >> $GITHUB_OUTPUT
          echo "Backend version: $ver"

      # JaCoCo report & threshold enforcement (fails job if <85%)
      - name: JaCoCo Report
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: backend/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Coverage Report
          update-comment: false
          # USER PREFERENCE: enforcement removed here.

      - name: Code Coverage Summary (Enforce Threshold)
        id: coverage_summary
        if: always()
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: backend/target/site/jacoco/jacoco.xml
          badge: true
          fail_below_min: true          # Enforcement now here
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '85 0'            # overall 85%, branch ignored

      - name: Copy JAR Artifact
        if: success()
        shell: bash
        run: |
          set -euo pipefail
          ver='${{ steps.projver.outputs.version }}'
          jarPath="backend/target/project-f-backend-${ver}.jar"
          if [[ ! -f "$jarPath" ]]; then
            echo "Jar $jarPath not found" >&2
            ls -1 backend/target || true
            exit 1
          fi
          cp "$jarPath" "project-f-backend-${ver}.jar"

      - name: Setup Flutter (stable)
        if: success()
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Cache Flutter Pub
        if: success()
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            frontend/.dart_tool
          key: flutter-pub-${{ runner.os }}-${{ hashFiles('frontend/pubspec.lock') }}
          restore-keys: |
            flutter-pub-${{ runner.os }}-

      - name: Flutter Pub Get
        if: success()
        working-directory: frontend
        run: flutter pub get

      - name: Flutter Build Web
        if: success()
        working-directory: frontend
        run: flutter build web --release

      - name: Upload Backend Jar Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: project-f-backend-*.jar
          if-no-files-found: error
          retention-days: 14

      - name: Upload Frontend Web Dist
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-web-dist
          path: frontend/build/web
          if-no-files-found: error
          retention-days: 14
